### ISSUE TITLE
Automate publishing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-test#102]
The current list of collaborators prevents me from publishing a new version:

![image](https://user-images.githubusercontent.com/22350/125604594-999bcc7d-7de3-46cc-a3a9-d48dcc4af429.png)

I've changed the CI to automate publishing https://github.com/microsoft/vscode-test/commit/f3b69c0ba910fcc20d25f330c09bf1baae11d18b. We still need:

- [ ] Create a `NPM_TOKEN` secret @connor4312
- [ ] Manually publish [1.6.0](https://github.com/microsoft/vscode-test/tree/v1.6.0) which exposes a generic `download` API, needed for our smoketest @connor4312

**Comment by joaomoreno** [comment]
Also, given automated publishing, I suggest we remove everyone from that list except @connor4312, especially @octref who doesn't work with us anymore.

**Comment by connor4312** [comment]
After publishing 1.6.0, we should also move to @vscode/test (or maybe @vscode/test-electron since we'll have a test-web too?).

**Comment by joaomoreno** [comment]
@connor4312 Can we publish now?

**Comment by connor4312** [comment]
yep I will do so after the current meeting

**Comment by connor4312** [comment]
I cannot manage package access since npm is having trouble, which also prevents me from being able to create a valid TOTP-less access token.

![image](https://user-images.githubusercontent.com/2230985/125841508-58d3391f-ccab-42c7-ab5b-555ae9f36552.png)

**Comment by connor4312** [comment]
Nevermind, found a workaround. 1.6.1 is published.
