### ISSUE TITLE
vscode-test install fails in GitHub Actions

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-test#103]
I'm trying to add GitHub Actions to the build for the [Docker extension](https://github.com/microsoft/vscode-docker), but running into some trouble. The install part of `vscode-test` fails with the following error:

```
> vscode-docker@1.15.5-alpha test /home/runner/work/vscode-docker/vscode-docker
> node ./out/test/runTest.js

Test options: {"extensionDevelopmentPath":"/home/runner/work/vscode-docker/vscode-docker","extensionTestsPath":"/home/runner/work/vscode-docker/vscode-docker/out/test/index","launchArgs":["/home/runner/work/vscode-docker/vscode-docker/src/test/test.code-workspace","--install-extension","ms-vscode.azure-account"],"extensionTestsEnv":{"DEBUGTELEMETRY":"1"}}
Downloading VS Code 1.58.2 from https://update.code.visualstudio.com/1.58.2/linux-x64/stableDownloaded VS Code 1.58.2 into /home/runner/work/vscode-docker/vscode-docker/.vscode-test/vscode-linux-x64-1.58.2
The futex facility returned an unexpected error code.

Exit code:   SIGABRT
Done
```

Full logs here: https://github.com/microsoft/vscode-docker/pull/3097/checks?check_run_id=3192312821

**Comment by connor4312** [comment]
Make sure a display is available, using xvfb is the easier way to do this. (Yes, this error from Electron is not particularly helpful.) Check out the docs here: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions

**Comment by bwateratmsft** [comment]
🤦‍♂️ Duh! I even knew that was needed for AZDO pipelines. Thanks @connor4312, sorry for the incorrect issue.
