### ISSUE TITLE
How to run tests with pre-installed extensions

### ISSUE THREAD

**Issue by Ascenio** [microsoft/vscode-test#104]
Hello. I'm developing an extension which depends on having [Dart](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code)'s extension installed as in `activationEvents`. But because the vscode which the test suite downloads is clean by default, my tests fail.

So I was wondering if there is any way to setup the editor to make it work.

**Comment by Ascenio** [comment]
Actually the problem might not be because of that, but I would still like to know the solution. :laughing:

**Comment by connor4312** [comment]
You can specify multiple `extensionDevelopmentPath`s in the call to runTests, which can include other extensions. Or you can pass in a `--extensions-dir` in the `launchArgs` if you have an existing extension installation directory.
