### ISSUE TITLE
`resolveCliPathFromVSCodeExecutablePath` for windows

### ISSUE THREAD

**Issue by xsro** [microsoft/vscode-test#108]
it seems the `resolveCliPathFromVSCodeExecutablePath` api not work in windows

in windows, the downloaded portable package has no folder `bin` in my case, but in my GitHub action workflow in works

**Comment by justinmk3** [comment]
- Same for macOS. 
- Tested with https://www.npmjs.com/package/@vscode/test-electron @ `2.1.3`

### Steps to reproduce:

```
import { resolveCliPathFromVSCodeExecutablePath } from '@vscode/test-electron'
...
const vsCodeCliPath = resolveCliPathFromVSCodeExecutablePath(vsCodeExecutablePath, 'darwin-x64-archive')
```

`vsCodeCliPath` contains:

    .vscode-test/vscode-darwin-1.65.0/Visual Studio Code.app/Contents/MacOS/bin/code

but the path on disk is:

     .vscode-test/vscode-darwin-1.65.0/Visual Studio Code.app/Contents/MacOS/Electron

**Comment by justinmk3** [comment]
@connor4312 this seems like a clear regression that affects all OSes. Would a PR to fix it be welcome?

**Comment by justinmk3** [comment]
For anyone blocked by this, try using `resolveCliArgsFromVSCodeExecutablePath` (notice: "args") instead of `resolveCliPathFromVSCodeExecutablePath` (notice: "path") .

**Comment by connor4312** [comment]
This is fixed
