### ISSUE TITLE
Test runs now failing with "Error: Invalid version *"

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-test#11]
My tests on Travis have started failing with this:

```
Current working directory: /Users/travis/build/Dart-Code/Dart-Code
Failed to run test with error:
Error: Invalid version *
    at /Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:179:31
    at step (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:36:23)
    at Object.next (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:17:53)
    at fulfilled (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
      Ended after: 0.511s
```

I have code that sets the version like this:

```
const codeVersion = process.env.RUN_CODE_VERSION === "DEV" ? "insiders" : "*";
```

I think `*` use to be valid to mean "the latest stable release" but I think in the latest change that has become broken. Looking at the source, maybe not setting a version at all will fix it, though I wonder if for compatibility it should remain supported (I think checking for `*` in [this condition](https://github.com/Microsoft/vscode-test/blob/90466866a22c5bfcf84ac201a26863cc0bede7e7/lib/download.ts#L122) *may* fix it).

**Comment by DanTup** [comment]
Simply dropping the `*` does solve my issue. If you don't plan on fixing this, it may be worth adding a note to the changelog or something.

**Comment by octref** [comment]
The public API does say "default to latest stable version":

https://github.com/Microsoft/vscode-test/blob/master/lib/runTest.ts#L24

`*` was used only for downloading latest VS Code API 

You can't even launch extension with `*` being the engines.vscode: https://github.com/Microsoft/vscode/issues/31574, so I won't fix this.

**Comment by DanTup** [comment]
> The public API does say "default to latest stable version":

My code doesn't directly call this API, my tests are run using the original test script from VS Code and haven't changed in a long time.

> You can't even launch extension with * being the engines.vscode

Sorry I wasn't clear where this came from. The value was being set in the `CODE_VERSION` env variable, not in `engines.vscode` (that has the lower version number I support). I think maybe this isn't right the right repository, maybe it should be https://github.com/Microsoft/vscode-extension-vscode. At some point, setting `CODE_VERSION` to `*` stopped working (I think maybe https://github.com/Microsoft/vscode-extension-vscode/commit/59f742e0ff173c9b59925a717e32f2753a1aadfc#diff-f900621cc6a1719b5473baf0191f297b was related to this, but it wasn't fixed in a way to support `CODE_VERSION` being set to `*` externally).

Anyway, I removed the `*` and all is good. I suspect it's unlikely to affect many (I don't think many people writing extensions are running tests against multiple versions such that they'd be setting `CODE_VERSION`).
