### ISSUE TITLE
the documented way of installing extensions for tests doesn't work

### ISSUE THREAD

**Issue by mkhl** [microsoft/vscode-test#121]
running the code cli as documented in https://code.visualstudio.com/api/working-with-extensions/testing-extension and on `util.resolveCliPathFromVSCodeExecutablePath` doesn't work since the 2.0.0 release because vscode is now invoked with a custom extensions dir (and user-data-dir, in `runTest.runTests`.

currently one can call `runTests` with `reuseMachineInstall` to work around this without depending on the internals of this package.
more invasive workarounds are supplying one's own extensions-dir and user-data-dir when installing extensions with the cli **and** when calling `runTests` (as part of `launchArgs`), or by importing `defaultCachePath` from the download submodule (which doesn't seem like it's supposed to be exposed) and supplying extensions-dir and user-data-dir just for the cli.

**Comment by connor4312** [comment]
Good find. I've added `resolveCliArgsFromVSCodeExecutablePath` which can be used instead. I updated the sample in this repo, and will update the docs now.
