### ISSUE TITLE
Test runner uses x64 on macOS ARM

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-test#122]
I was wondering why test execution was so slow on my M1 MacBookPro and then noticed how this module missed to adopt support for our macOS ARM/Universal builds. I think this should be addressed as soon as possible.

Slightly related, we have Linux/Windows ARM builds as well, so the same could apply there?

**Comment by connor4312** [comment]
I've added logic for this for OS X and Windows, however I do not have ARM devices to test on. Please verify this on `@vscode/test-electron@2.0.3` 🙂

**Comment by bpasero** [comment]
@connor4312 thanks for the prompt fix, I verified this on macOS just now.

But what worries me is that our Yo generator pins the `@vscode/test-electron` dependency to a very old version: `^1.6.2`.

@aeschli can you update the generator?

**Comment by aeschli** [comment]
@bpasero Pushed generator-code@1.6.6

**Comment by bpasero** [comment]
Thanks 🤝
