### ISSUE TITLE
downloadAndUnzipVSCode returns invalid executable path

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode-test#124]
While running under WSL2 and explicitely requesting the Windows version of vscode, I got a big surprise: the windows version was downloaded but the returned path was towards Linux one.

```typescript
    const executable = await downloadAndUnzipVSCode(
      'stable',
      'win32-x64-archive'
    );
```

```
Found /mnt/c/Users/sorin/c/a/vscode-ansible/.vscode-test/vscode-win32-x64-archive-1.63.2. Skipping download.
Print returned executable: /mnt/c/Users/sorin/c/a/vscode-ansible/.vscode-test/vscode-win32-x64-archive-1.63.2/VSCode-linux-x64/code
```

While when called without any arguments I would have expected that kind of returned value, it came as a big surprise to get linux when requested windows.

Expected return value:
```
.../.vscode-test/vscode-win32-x64-archive-1.63.2/code.cmd
```
If you look at what was returned versus what I was expecting, you will see an extra folder that does not exists on disk `VSCode-linux-x64/` and also a wrong extension for the executable as for windows it should have being `code.cmd` instead of just `code`.

**Comment by connor4312** [comment]
Good catch!
