### ISSUE TITLE
mark vscode-test package as deprecated on npm and redirect to @vscode/test-electron

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-test#126]
For example https://www.npmjs.com/package/opn has this useful banner that points users to https://www.npmjs.com/package/open

![npm-banner](https://user-images.githubusercontent.com/23744935/152875297-65ebb77a-2490-4d55-86cf-ad1efd5617c1.png)

**Comment by connor4312** [comment]
Done

**Comment by SimonSiefke** [comment]
Thank you!
