### ISSUE TITLE
 Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-test#127]
I'm seeing this error in the github actions logs very often:

```
[2287:0204/174506.688134:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

For example [here](https://github.com/formulahendry/vscode-auto-rename-tag/runs/5121719939?check_suite_focus=true) the error is logged 58 times 

![logs-2](https://user-images.githubusercontent.com/23744935/153496053-fc29a393-73da-49cd-9441-d410f525425f.png)

Fortunately this is not a critical error, as all the tests are still passing, it's just a bit noisy 🙂

**Comment by connor4312** [comment]
@deepak1556 any ideas?

**Comment by lovettchris** [comment]
I get the same thing in [my tests](https://github.com/leanprover/vscode-lean4/runs/5212963357?check_suite_focus=true), love to know the answer...

**Comment by deepak1556** [comment]
This is an issue with your CI setup, the runtime usually makes connection to the login session bug and the system bus for some of its components and from the error looks like you might have an incorrect value for `DBUS_SESSION_BUS_ADDRESS`. You can confirm this by running the following sample in your CI,

```
#include <iostream>
#include <dbus/dbus.h>

int main() {
    DBusError error;
    dbus_error_init(&error);
    DBusConnection* bus = dbus_bus_get(static_cast<DBusBusType>(DBUS_BUS_SESSION), &error);
    if (!bus) {
        std::cerr << "Failed to connect with session bus : "
                  << (dbus_error_is_set(&error) ? error.message : ""); 
    } else {
        dbus_connection_unref(bus);
    }

    bus = dbus_bus_get(static_cast<DBusBusType>(DBUS_BUS_SYSTEM), &error);
    if (!bus) {
        std::cerr << "Failed to connect with system bus : "
                  << (dbus_error_is_set(&error) ? error.message : ""); 
    } else {
        dbus_connection_unref(bus);
    }
    dbus_error_free(&error);
    return 0;
 }
```

The dbus connection from the runtime is not a hard requirement, so you can try unsetting the `DBUS_SESSION_BUS_ADDRESS` environment variable or ignore the above logs.

**Comment by lovettchris** [comment]
Might be related to this: https://github.com/electron/electron/issues/31981

**Comment by aeisenberg** [comment]
Sorry for the link spam here. I had thought this issue could address my problem, but it is not.
