### ISSUE TITLE
Can you support 'workbench.action.closeFolder'

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode-test#131]
I have a test that needs to be able to do this:
```
await vscode.commands.executeCommand('workbench.action.closeFolder');
```

But when I do something goes screwy and the test auto-restarts in a new vs instance or something.

**Comment by connor4312** [comment]
This is because the window reloads, resulting in a new extension host -- the extension host where tests are running gets torn down. It's not feasible to support this case.

**Comment by lovettchris** [comment]
I figured it would be something like that, well if this one gets fixed then I won't need closeFolder:
https://github.com/microsoft/vscode-test/issues/130
