### ISSUE TITLE
VS Code 1.66.0 doesn't terminate after running tests

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/vscode-test#138]
Today on the VS Code C# extension we noticed on [this PR](https://github.com/OmniSharp/omnisharp-vscode/pull/5135) that our that our GitHub CI check was not completing (a good reminder to add timeouts). I manually canceled the run. Checking the logs I saw we started testing against the new 1.66.0 release. Rerunning gave the same result. 

[Canceled run logs](https://github.com/OmniSharp/omnisharp-vscode/actions/runs/2066631853):
```
...
Wed, 30 Mar 2022 18:27:32 GMT Exit code:   0
Wed, 30 Mar 2022 18:27:32 GMT Done
Wed, 30 Mar 2022 18:27:32 GMT
Wed, 30 Mar 2022 22:37:06 GMT Error: The operation was canceled.
```

We were able to work around this by specifying version 1.65.0 when running tests.

**Comment by connor4312** [comment]
Thanks for the issue! The "done" log is fired after the VS Code process exits, directly before returning

https://github.com/microsoft/vscode-test/blob/99cc74cee0ea1d84f9df950b4e25133114f3c072/lib/runTest.ts#L187

I noticed that first three integrations tests ran and passed successfully, is there anything special happening with the one that times out (`BasicRazorApp2_1`)?

**Comment by JoeRobich** [comment]
@connor4312 Interesting. No, that run executes the same tests as the others, only the test workspace is different.

**Comment by Divlo** [comment]
Having the same issue.
If it can help to debug: here is the GitHub Action run: https://github.com/standard/vscode-standard/runs/5822268604

**Comment by JoeRobich** [comment]
I have not seen this behavior with recent releases. Closing for now. Will reopen with more details if it reoccurs.

**Comment by JoeRobich** [comment]
I was mistaken. This issue still exists with 1.67.2.

GitHub Action run: https://github.com/OmniSharp/omnisharp-vscode/runs/6495754290

```
Wed, 18 May 2022 19:36:46 GMT Exit code:   0
Wed, 18 May 2022 19:36:46 GMT Done
Wed, 18 May 2022 19:55:51 GMT Error: The operation was canceled.
```

Workaround is to specify version 1.65.0 when running tests.

**Comment by connor4312** [comment]
@deepak1556 anything you know about that could cause this?

I would assume this is a(n unknown) vscode-test bug, but the difference between versions of VS Code itself is strange and suspect.

**Comment by kubukoz** [comment]
Still seeing this in 1.73.1.

**Comment by connor4312** [comment]
I noticed this in js-debug as well. I used [wtfnode](https://www.npmjs.com/package/wtfnode) and noticed there were a few sockets still open. I've applied a fix for this in a version I'm about to publish, 2.2.3. Please let me know if you still encounter this issue after updating.

**Comment by kubukoz** [comment]
I was running on Mac btw, so it's not just a Windows issue.

**Comment by connor4312** [comment]
Sorry, I think this may happen on other platforms as well. Just the thing that triggers it for me is a test that only runs on Windows.
