### ISSUE TITLE
runTest uses incorrect platform x64 on arm64 

### ISSUE THREAD

**Issue by Josverl** [microsoft/vscode-test#141]
The VSCode integration test using @vscode/electron-test fails to find the correct vscode-test runtime for the platform.
it appears that the download is correct , but then the launch is using a different path 

- downloaded version : Downloaded VS Code 1.66.2 into 
   `/home/jos/pymakr-vsc/.vscode-test/vscode-linux-x64-1.66.2`
- tries to launch the **linux-x64** version:  
  `/home/jos/pymakr-vsc/.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-x64/code`
same configuration runs correct 

# Expected 
- tries to launch: the downloaded **linux-arm64** version 
 `/home/jos/pymakr-vsc/.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-arm64/code`

npm script
``` 
"test:integration": "node test/utils/setup.js --run-setup && node ./test/runTest.js test/workspaces/integration --disable-extensions --extensionTestsPath=test/suite/index",
`
```

Testrun : 
```bash
jos@Pi4:~/pymakr-vsc$ npm run test:integration

> pymakr-preview@2.8.6 test:integration /home/jos/pymakr-vsc
> node test/utils/setup.js --run-setup && node ./test/runTest.js test/workspaces/integration --disable-extensions --extensionTestsPath=test/suite/index

Downloading VS Code 1.66.2 from https://update.code.visualstudio.com/1.66.2/linux-arm64/stable
Downloading VS Code [==============================] 100%Downloaded VS Code 1.66.2 into /home/jos/pymakr-vsc/.vscode-test/vscode-linux-x64-1.66.2
Test error: Error: spawn /home/jos/pymakr-vsc/.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-x64/code ENOENT
Exit code:   -2
Failed to run tests
```

runTest.js is using the [boilerplate code](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script)

@jakobrosenberg

Version info:
--------------

##Code
code 1.66.0
e18005f0f1b33c29e81d732535d8c0e47cafb0b5
arm64

## Test package
@vscode/test-electron": "^2.1.3"

## OS
OS : Linux Pi4 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

## node
Node v14.19.0

**Comment by jakobrosenberg** [comment]
Currently integration tests only work if run through the debugger (F5). It seems that the Pymakr instance otherwise isn't able to be returned to the testing suite.

There might be a fix to this.
