### ISSUE TITLE
`code --install-extension Prisma.prisma-insider@[version]` returns `Server returned 503`

### ISSUE THREAD

**Issue by Jolg42** [microsoft/vscode-test#142]
We are seeing many `Server returned 503` errors from this command in our CI (GitHub Actions):
```
/workspaces/language-tools/.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-x64/bin/code --install-extension Prisma.prisma-insider@31.0.852
```
This command is called for each new version (with the corresponding version)

The full source code is located at https://github.com/prisma/language-tools/blob/main/scripts/e2eTestsOnVsix/install_extension.js

The GitHub Action workflow runs:
https://github.com/prisma/language-tools/actions/workflows/e2e_published_vsix.yml
Error log example: https://github.com/prisma/language-tools/runs/6075977680?check_suite_focus=true#step:5:31
```
{
  status: 1,
  signal: null,
  output: [ null, 'Installing extensions...\n', 'Server returned 503\n' ],
  pid: 1875,
  stdout: 'Installing extensions...\n',
  stderr: 'Server returned 503\n'
}
```
<img width="948" alt="Screen Shot 2022-04-19 at 12 40 45" src="https://user-images.githubusercontent.com/1328733/163986731-38f18e53-585a-401c-ac4f-8075eded17ab.png">

Do you have an idea about what this error is and how to avoid it?

**Comment by Jolg42** [comment]
I could not reproduce locally, and the CI indicates that this might be flaky, though it happened a lot in the last few hours (see screenshot)

**Comment by isidorn** [comment]
Marketplace service is facing service issues the last couple of days. We are aware of this and we are looking into it.
Soon there should be an issue with more details in the https://github.com/microsoft/vsmarketplace repository

Thank you for your understanding

**Comment by Jolg42** [comment]
@isidorn @connor4312 Ok makes sense now.

Could the error message be improved, maybe?

Because it's not saying much about what it is (just a "Server" and a "503" but nothing else that could help, like the URL of the server that triggered that error.)

**Comment by Jolg42** [comment]
After a random Google search, I found the status page at https://vsstatus.visualstudio.com/ and everything is green there 🤔

**Comment by isidorn** [comment]
https://status.dev.azure.com/_event/302592133
This should have more details. I do not know why those two status pages are not in sync though - sorry!
