### ISSUE TITLE
"Failed to download and unzip VS Code insiders"

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-test#15]
I'm seeing this on Travis this morning, both on Linux and macOS. The error doesn't really give much info on what went wrong (looks like the [real error isn't included](https://github.com/Microsoft/vscode-test/blob/b8813110b229fa1a524650c16ec521df42b7893d/lib/download.ts#L149) in the output), but the URL that's output seems to be 404s, for ex:

https://update.code.visualstudio.com/latest/darwin/insiders

I don't know if this is an issue here (eg. wrong URL) or if something may have gone wrong with the insiders builds? (the link on the website seems to work ok)

```
Current working directory: /Users/travis/build/Dart-Code/Dart-Code
Downloading VS Code insiders into .vscode-test/vscode-insiders.
Downloading VS Code from: https://update.code.visualstudio.com/latest/darwin/insiders
Failed to run test with error:
Error: Failed to download and unzip VS Code insiders
    at /Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:207:27
    at step (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:36:23)
    at Object.throw (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:17:53)
    at rejected (/Users/travis/build/Dart-Code/Dart-Code/node_modules/vscode-test/out/download.js:9:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
      Ended after: 0.881s
```

**Comment by octref** [comment]
Was fixed in https://github.com/Microsoft/vscode-test/commit/408d9e27ca0f68e0a3906ad0e70875bb99b26c96, please update.

**Comment by DanTup** [comment]
@octref I don't have an explicit dependency on this, I presume it's coming via the [vscode](https://www.npmjs.com/package/vscode) package, though I can't actually find an explicit reference in the `package.json` in the linked repo (Microsoft/vscode). Do you know where it is? Does it need updating there?

(I'm not sure what's triggered me getting this version today though 🤔)

**Comment by octref** [comment]
I see, my bad. Let me upgrade `vscode` module too.

**Comment by octref** [comment]
Published new `vscode` version.

**Comment by DanTup** [comment]
Great, thanks!
