### ISSUE TITLE
Tests profiling

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode-test#155]
Hi!

  I can run `node --cpu-prof out/test/runTest.js` to profile test runner, but I can't figure out how to profile my extension. My extension is running slow only under tests, so I would like to understand what is going on. Any tips would be appreciated.

**Comment by connor4312** [comment]
You can use the [inspector api](https://nodejs.org/api/inspector.html) to trigger a profile run. Though it could be interesting to have built-in support for it.
