### ISSUE TITLE
vscode.extensioin.getExtension is undefined when running test

### ISSUE THREAD

**Issue by loin3** [microsoft/vscode-test#157]
When I'm runninng tests while developing vscode extension, I got error `TypeError: Cannot read properties of undefined (reading 'activate')`.

Is there any possibilities that test code tried to get extension and activate before extension is fully installed when extension is heavy?

```
suite('Extension Test Suite', () => {
    let extensionContext: ExtensionContext;
    suiteSetup(async () => {
        await extensions.getExtension('test.vscode-extension')!.activate();
        extensionContext = (global as any).testExtensionContext;
    });

    test('state', () => {
        const extension = vscode.extensions.getExtension('test.vscode-extension');
        assert.ok(!!extension);
        assert.ok(!!extensionContext);
        assert.ok(!!extensionContext.globalState);
    });
});
```

**Comment by connor4312** [comment]
I'm not able to reproduce this, can you upload a sample repo of a place you see where this happens?

**Comment by loin3** [comment]
Oh.. I'm sorry.
I am using TS, but I did not enter the extensionDevelopmentPath that matches the changes with JS, but I entered it based on TS, so it was wrong.
