### ISSUE TITLE
How to get extension context

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode-test#159]
I try to save the context when extension activate
```ts
import * as vscode from 'vscode';

let context: vscode.ExtensionContext;

export function storeContext(ctx: vscode.ExtensionContext) {
  context = ctx;
}

export function getContext() {
  return context;
}
```

```
export function activate(ctx) {
   storeContext(ctx)
}
```
But the `activate` funtion wasn't called

**Comment by connor4312** [comment]
Please see our documentation on [activation events](https://code.visualstudio.com/api/references/activation-events) to learn when/how extensions activate.
