### ISSUE TITLE
Unable to activate extension with `extensionDependencies`

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-test#164]
I seem to be unable to run tests with an extension that has dependencies.

@vscode/test-electron: 2.1.5
vscode-insiders: 1.72.0-insider
platform: windows

For reference, our extension has a dependency on another extension in our `package.json` file:
```
"extensionDependencies": [
        "ms-dotnettools.vscode-dotnet-runtime"
],
```

Our test run script looks like this:
```
        // The folder containing the Extension Manifest package.json
        // Passed to `--extensionDevelopmentPath`
        const extensionDevelopmentPath = path.resolve(__dirname, "../../../");

        // The path to the extension test script
        // Passed to --extensionTestsPath
        const extensionTestsPath = path.resolve(__dirname, "./suite/index");

        const platform = computePlatform();
        const channel = "insiders";
        const vscodeExecutablePath = await downloadAndUnzipVSCode(channel, platform);

        const cliPath = resolveCliPathFromVSCodeExecutablePath(vscodeExecutablePath, platform);

        // Install .NET Install Tool for Extension Authors extension
        spawnSync(cliPath, ["--install-extension", "ms-dotnettools.vscode-dotnet-runtime"], {
            encoding: "utf-8",
            stdio: "inherit"
        });

        // Download VS Code, unzip it and run the integration test
        await runTests({ vscodeExecutablePath, extensionDevelopmentPath, extensionTestsPath });
```

In the test run output, I see 
```
Installing extensions...
Extension 'ms-dotnettools.vscode-dotnet-runtime' is already installed.
```

However, the extension isn't showing up as installed for the spawned test vscode instance:
![image](https://user-images.githubusercontent.com/8560030/188211987-f8c9f850-8272-4404-8629-86273b67d3a0.png)

Tests work as expected if I remove the dependency in package.json.

**Comment by connor4312** [comment]
You either need to set `runTests` in the `runTest`, or specify an `--extensions-dir` both when calling `--install-extension` and `runTest`. By default @vscode/test-electron does not use the system install, which is where you're attempting to install the extension.

**Comment by pwang347** [comment]
@connor4312 makes sense, I suppose the fix is to use `resolveCliArgsFromVSCodeExecutablePath` instead of `resolveCliPathFromVSCodeExecutablePath` then (that seems to be the only difference I see between my code and the sample [here](https://github.com/microsoft/vscode-test/blob/main/sample/test/runTest.ts#L70)).
