### ISSUE TITLE
Current working directory inconsistent across platforms

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-test#17]
When running `node node_modules/VSCode/bin/test` with reporter options to save a file for subsequent upload (see #151 for context), I'm finding that the current working directory is inconsistent. In my _src/test/index.ts_ I have something like this:

```typescript
const opts = {
  reporter: 'mocha-junit-reporter',
  reporterOptions: {
    mochaFile: './test-results.xml'
  },
  ui: 'tdd',
  useColors: true
};

testRunner.configure(opts).
```

On Windows, this file ends up in _.vscode-test\stable\test-results.xml_. On Linux (and I presume MacOS, since Azure DevOps is reporting during test results upload that file cannot be found), the file gets saved to my project root _./test-results.xml_. Given I am testing both stable and insiders versions of Code, I prefer the Windows approach but being consistent in any fashion would make CI/CD workflows much easier to create and maintain.

**Comment by octref** [comment]
@heaths This should be gone after release of: [Release notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#splitting-vscode-package-into-typesvscode-and-vscode-test) | [Docs](https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md)

Also, why aren't you using absolute paths?

**Comment by heaths** [comment]
What of those docs is supposed to tell me whether how you handle (or don't) the current working directory has changed or not? Not having looked at your code for this project, I honestly can't answer that. From what I see in the docs, it seems you did some refactoring. Not sure how that is going to affect the CWD.

As for now using absolute paths, because in other test systems (e.g. MSBuild, which defaults the CWD to the currently building project) I don't have to. I can try generating an absolute path based on, for example, `__dirname`, but doesn't seem to absolve that CWD handling of your test runner is inconsistent across platforms.

**Comment by octref** [comment]
Actually you are correct. This is still unfixed: https://dev.azure.com/zhenhwu/vscode/_build/results?buildId=40

**Comment by octref** [comment]
This is actually a VS Code core problem. Upstream issue here: https://github.com/microsoft/vscode/issues/47195
