### ISSUE TITLE
VSCode Test Runner does not install or run correctly in Azure Dev Ops Builds

### ISSUE THREAD

**Issue by jjaguirre394** [microsoft/vscode-test#170]
VS Code Version: Latest stable
OS Version: Latest Azure DevOps Windows Container
Steps to Reproduce:

1. Create a testing script that uses the [VsCode Test Runner](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script)
2. Attempt to run this script from Azure Dev Ops and produce an xunit test report.
3. Notice the following error:
[10480:1020/203958.625:ERROR:network_change_notifier_win.cc(225)] WSALookupServiceBegin failed with: 0
Exit code: 3221225477
Failed to run tests

![image](https://user-images.githubusercontent.com/4118587/197074413-770ef3e8-1911-4a2f-98f3-91bcc5b762cb.png)

NOTE: This also did not work on Linux based container builds on Azure Devops. If you would like access to our pipeline definition or build run, please let me know (internal repo and build).

The tests run fine locally.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/164183
