### ISSUE TITLE
Add support for executing commands

### ISSUE THREAD

**Issue by ghaschel** [microsoft/vscode-test#171]
My tests work from Launch.json, but won't work when launching from the command line, as `vscode.commands` comes as undefined

**Comment by connor4312** [comment]
This is not an issue with vscode-test. StackOverflow may be a more appropriate forum for your question.

**Comment by ghaschel** [comment]
I don't think this would be appropriate for Stackoverflow as I am writing the tests using the api available from vscode, it works if I launch my tests from the Vscode taskbar, but not if from the command line.

`vscode.command` simply do not exist when launching from the terminal. It is undefined. So it means, reduced api coverage when using it from the terminal, thus compromising CI
