### ISSUE TITLE
Add a check to make sure an "existing installation" actually is fully available and works

### ISSUE THREAD

**Issue by zimmski** [microsoft/vscode-test#174]
I just debugged a very curious CI failur of our VSC extension. It seems that vscode-test, specifically "downloadVSCode" and friends, does not check if an existing installation (or a just downloaded installation) actually is complete and therefore even usable.

This happend:
- Under macOS ARM64
- Cache path `/var/folders/xk/mzfhf6ws4vg9h7x4sltts8lw0000gn/T/.vscode-test/` (because that is what `os.tmpdir()` provides as base)
- `/var/folders/xk/mzfhf6ws4vg9h7x4sltts8lw0000gn/T/.vscode-test/vscode-darwin-arm64-1.72.2/Visual Studio Code.app/Contents/MacOS/Electron` did not exist
- However, `/var/folders/xk/mzfhf6ws4vg9h7x4sltts8lw0000gn/T/.vscode-test/vscode-darwin-arm64-1.72.2/Visual Studio Code.app/Contents/MacOS` the directory did exist.

There were actually a lot of files missing when i compared it to a fresh install. And i am not sure how these files were deleted, because we do not delete files in that directory.

In any case, i think vscode-test should check the full filesystem tree of the installation to have a specific checksum. This can be cheap (just files and sizes, maybe permissions). If the check fails, the installation should be deleted and downloaded again.

This logic would have helped a lot: i assumed the problem was somewhere else since the message `Found existing install in ... Skipping download` suggested to me that the installation is valid.

**Comment by symmb** [comment]
We've actually implemented our own download function in the meantime which stores the archive files in the cache path, and verifies the checksum and extracts a new copy before every run. So in pseudo-code the behavior is:

  - Fetch latest version info
  - Until we have an archive file for the current platform with the right checksum (or a retry limit is exceeded):
    - Download the archive file to the cache path
  - Extract the archive from the cache path to a separate "installation path" (which will be used to execute VS Code; the archive in the cache path is kept)

Is there any interest in getting that upstreamed? Right now we've just added it to our own code, so it's not integrated into the library yet but I can open a PR for it if desired.

**Comment by connor4312** [comment]
We stream extraction of the vscode download when possible, which speeds things up a good amount when available (on any platform except macOS). I would rather not get rid of that. But simply running `code --version` and checking that the output is sane is probably a good step in verifying whether the installation is good or not.

**Comment by zimmski** [comment]
If anybody is running into the same problems: here is how we solved it https://symflower.com/en/company/blog/2023/vscode-test-installation/ You can find the full code there as well.

@connor4312 not sure how to proceed with this issue. We need some form of verification of the installation and cache, otherwise we are running into problems. Can you take a look at what we did and propose on how this can be upstreamed?
