### ISSUE TITLE
2.2.1 requires node >= 16.0 but the documentation still says 12

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-test#181]
The newly released 2.2.1 version of the `@vscode/test-electron` package requires [node >= 16](https://github.com/microsoft/vscode-test/blob/683cc520be8866e87dc3f9e9605b0782e9a497fa/package.json#L12), but the readme still says `Node >= 12.x`.

Will this requirement be loosened, or should projects either upgrade to Node 16 or pin vscode/test-electron to 2.2.0?

**Comment by dfreeman** [comment]
Node 14 is still under LTS maintenance, though, and dropping support for it in a patch release wasn't ideal 😕
