### ISSUE TITLE
Dynamically change main entry point in package.json when running tests

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode-test#185]
My extension is bundled using esbuild and I set the produced `out/main.js` file as `main` entry point in package.json.

For testing I do not use esbuild, but tsc, which produces different files and I have to change the main entry point to `out/extension/extension.js`. Doing this manually is obviously not a good solution, so I wonder if and how I can override this when starting the tests with `@vscode/test-electron`?

**Comment by connor4312** [comment]
We don't support this, and it's unlikely that we would do it in this way. Some extensions compile their package.json into a subdirectory and launch out of there.

That said I understand the pain of testing when using a bundler to produce the extension. I want to find a homogenous solution to this case, but this approach is not complete. https://github.com/microsoft/vscode-test/issues/186

**Comment by M00TSDNS** [comment]
Testability would be severely impacted by changing the main entry point. What if the `test` entry point meets the functional requirement of your test suite, but `main` doesn't? (E.g. does not error out on running `activate`)

**Comment by mike-lischke** [comment]
I'm all ears @M00TSDNS for a better solution, but changing the main entry point was the only way I could get both variations to work.
