### ISSUE TITLE
Controlling activationEvents when testing extensions?

### ISSUE THREAD

**Issue by dggsax** [microsoft/vscode-test#218]
I have an extension with the following activation events configuration that I'm testing:

```json
{
    "activationEvents": [
        "onStartupFinished"
    ],
}
```

When I start my tests with `runTests` from `@vscode/test-electron`, I see that as soon as the test host instance of VSCode starts up the extension I'm testing initializes and runs through the activation process (as expected).

That being said, I'm interested in testing several different activation scenarios based on things like the extension context's globalState. 

Is there an approach or paradigm that allows me to control when the `onStartupFinished` event is actually sent in the test instance of VSCode?

**Comment by connor4312** [comment]
No, there's no such event. `onStartupFinished` is intentionally opaque and we don't allow further customization.
