### ISSUE TITLE
typo CHANGELOG.md is 2023 year

### ISSUE THREAD

**Issue by CoffeeChaton** [microsoft/vscode-test#223]
<https://github.com/microsoft/vscode-test/blob/main/CHANGELOG.md#223--2022-01-30>

v2.2.3 ~ v2.3.3 is 2023?

**Comment by apupier** [comment]
it was fixed with this unrelated commit https://github.com/microsoft/vscode-test/commit/6d096d4ff63489fb51d877d2d65151d5a1918119
