### ISSUE TITLE
Support running tests using a version of VSCode that is already running

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-test#24]
The largest disadvantage to switching to using this library vs the traditional debug launch configuration is the loss of the ability to run tests in the same version of VSCode that you are launching the debug configuration from. The [Extension Testing](https://code.visualstudio.com/api/working-with-extensions/testing-extension#using-insiders-version-for-extension-development) page suggests to just use Insiders for testing extensions, which is fine if you only ever want to test in Stable, but I would personally like to run suites for both. Now the only way to do that is to close VSCode and run the tasks from the terminal.

**Comment by octref** [comment]
> the loss of the ability to run tests in the same version of VSCode that you are launching the debug configuration from

> run suites for both. Now the only way to do that is to close VSCode and run the tasks from the terminal.

That's the same case for using `vscode` NPM module. You can only do this through launch config, and this hasn't changed between `vscode` and `vscode-test`.

**Comment by jcrben** [comment]
@octref confused by this - `vscode` is deprecated per https://www.npmjs.com/package/vscode

https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode does not discuss how to use `vscode-test` to run from `launch.json`, does it?
