### ISSUE TITLE
run tests with --watch

### ISSUE THREAD

**Issue by nachocab** [microsoft/vscode-test#243]
Is it possible to configure `runTests.ts` to run continuously? I currently get kicked out when the tests are over:

```
  1 passing (16ms)
[main 2023-11-09T16:24:27.090Z] Extension host with pid 5444 exited with code: 0, signal: unknown.
Exit code:   0
Done
```

**Comment by connor4312** [comment]
--watch is supported by the test CLI: https://github.com/microsoft/vscode-test-cli
