### ISSUE TITLE
error when running on WSL2

### ISSUE THREAD

**Issue by devmanbr** [microsoft/vscode-test#245]
what's the point of Microsoft offering the WSL and its own tools (for this case, `@vscode/test-electron`) not working with it?

I've been trying to get it to work for days, and the best I can get is the same output in the terminal:
```
Exit code: SIGTRAP
Failed to run tests
```

try running tests in any extension, including the sample, and you will have the same result. on WSL it just doesn't work.

Can anyone offer me some light on how to solve this?

Testing manually is a nightmare.

**Comment by connor4312** [comment]
Are you running an X Window server or xvfb? Can you launch VS Code itself in WSL? That is a required for running tests in WSL.
