### ISSUE TITLE
Mocha parallel mode issue

### ISSUE THREAD

**Issue by AlexCannonball** [microsoft/vscode-test#253]
Hello,

My tests are working fine in Mocha serial mode on Windows. However, if I try parallel mode in `test/suite/index.ts` like this:

```ts
export async function run(): Promise<void> {
  const mocha = new Mocha({
    parallel: true,
    jobs: 2,
    ui: 'bdd',
    checkLeaks: true,
    color: true,
    inlineDiffs: true,
    reporter: 'min'
  });
...
```
I'm getting an error:

> Uncaught Error: Cannot find module 'vscode'

What am I doing wrong?

**Comment by connor4312** [comment]
Mocha runs parallel-mode tests in separate worker processes. These cannot access the VS Code API, and doing so is unfortunately not possible.
