### ISSUE TITLE
MacOS Electron EACCES error when using `runTests`

### ISSUE THREAD

**Issue by AndrewJakubowicz** [microsoft/vscode-test#254]
### Issue

A previously working test setup using `import { runTests } from "@vscode/test-electron";` worked. However recently it has stopped working.

To reproduce the issue:

1. Clone https://github.com/runem/lit-analyzer
2. Then from within `lit-analyzer`, run `npm ci && npm test`.

The expectation is that tests run. Instead, the following error occurs:

```
Downloading VS Code [=============================-] 100%Downloaded VS Code 1.85.1 into /Users/.../lit-analyzer/packages/vscode-lit-plugin/.vscode-test/vscode-darwin-1.85.1
Test error: Error: spawn /Users/.../lit-analyzer/packages/vscode-lit-plugin/.vscode-test/vscode-darwin-1.85.1/Visual Studio Code.app/Contents/MacOS/Electron EACCES
Exit code:   -13
Failed
❌ [packages/vscode-lit-plugin:test:normal] Failed with exit status 1
```

### Workaround

This is not an ideal workaround, but it can work to unblock. The issue seems to stem from the stable version of vscode installed.

Within `node_modules/@vscode/test-electron/out/download.js` there is a function:

```js
async function fetchLatestStableVersion() {
    const versions = await request.getJSON(vscodeStableReleasesAPI);
    if (!versions || !Array.isArray(versions) || !versions[0]) {
        throw Error('Failed to get latest VS Code version');
    }
    // Change versions[0] to versions[2] to fix the issue.
    return versions[0];
}
```

Using `versions[2]` resolves the issue.

### Why

The latest stable release is queried from the URL: https://update.code.visualstudio.com/api/releases/stable
As of writing this issue, the access error reproduces on versions `"1.85.1"` and `"1.85.0"`. The issue is resolved by forcing the installation of stable version `"1.84.2"`.

### Environment details

OS: MacOS
Node: v20.10.0
npm: 10.2.3

Thank you!

**Comment by connor4312** [comment]
Based on the package-lock, that repo is using 2.1.3 of test-electron. This should already be fixed in the latest 2.3.8. Note if you have local installs that were already 'broken', you'll want to delete the `.vscode-test` directory after updating so that they're reinstalled. Please let me know if your issue persists after updating.

**Comment by AndrewJakubowicz** [comment]
Issue resolved! Thank you

**Comment by connor4312** [comment]
Please share a link to the build/repo where you see this, thanks

**Comment by connor4312** [comment]
I found an issue that can cause extraction to fail if you're invoking the runner from the VS Code UI using the extension. Note that you will need to delete `.vscode-test` after updating to clear out the cached version.

**Comment by connor4312** [comment]
Can you please link a Github action run where you see this happening?

**Comment by connor4312** [comment]
Are you trying to run the Windows version of VS Code on macOS?

That will not work. You need to run the macOS version of VS Code on macOS.
