### ISSUE TITLE
Unable to use global fixtures.

### ISSUE THREAD

**Issue by bthornton191** [microsoft/vscode-test#259]
According to the mocha [documentation](https://mochajs.org/#global-fixtures), I can define a global setup fixture like so...

```javascript
// fixtures.cjs

exports.mochaGlobalSetup = function() {
   console.log('Start all tests')
}
```

Then point to this using `require` in the mocha options...

```javascript
// .vscode-test.js
const { defineConfig } = require('@vscode/test-cli');
module.exports = defineConfig({
    files: 'test/**/*.test.js',
    workspaceFolder: 'test',
    mocha: {
        require: path.join(__dirname, 'test', 'global_fixture.cjs'), // <-----
    }
});
```

**Expected behavior:** `mochaGlobalSetup` should run prior to running my tests
**Actual behavior:** `mochaGlobalSetup` never runs.

**Comment by connor4312** [comment]
That part of the mocha API seems to only take effect when running parallel tests, based on the code and issue when it was documented. However we could do a little legwork to support it ourselves.

There's a `preload` option that we currently have from before they documented that, but we don't look at exports at the moment. That's easy to do.

**Comment by bthornton191** [comment]
Thanks @connor4312 . I found the `preload` option and my current workaround is to use the `preload` option to run my fixture.cjs file and  run `mochaGlobalSetup` instead of exporting it like so:

```javascript
// fixtures.cjs

mochaGlobalSetup = function() {
   console.log('Start all tests')
}

mochaGlobalSetup()
```

This workaround seems to work fine for setup. **Unfortunately**, there is no way to run a global _tear down_ function which mocha would run if you export a `mochaGlobalTeardown` function.

> but we don't look at exports at the moment. That's easy to do.

This would be much appreciated! 🙏

**Comment by connor4312** [comment]
yep, this'll be fixed in https://github.com/microsoft/vscode-test-cli/pull/23 which will be released shortly
