### ISSUE TITLE
github actions: Failed to get win32 version

### ISSUE THREAD

**Issue by pizza-777** [microsoft/vscode-test#261]
I've got [the error from github actions](https://github.com/pizza-777/everscale-solidity-vscode-extension/actions/runs/8143964702/job/22257006819#step:6:22):
```sh
Failed to get VS Code archive location
Failed to run tests
Downloading VS Code 1.87.0 from https://update.code.visualstudio.com/1.87.0/win32-archive/stable
Error: Process completed with exit code 1.
```

**Comment by connor4312** [comment]
Please update to the latest version of @vscode/test-electron for the fix.
