### ISSUE TITLE
`--install-extension` flag not working on Windows with Node 20.12.2

### ISSUE THREAD

**Issue by jfeingold35** [microsoft/vscode-test#266]
I am using the following code
```
import * as path from 'path';
import * as cp from 'child_process';
import {
	downloadAndUnzipVSCode,
	resolveCliArgsFromVSCodeExecutablePath,
	runTests
} from '@vscode/test-electron';

import { EXTENSION_PACK_ID } from '../lib/constants';

async function main() {
	try {
		// The folder containing the Extension Manifest package.json
		// Passed to `--extensionDevelopmentPath`
		const extensionDevelopmentPath = path.resolve(__dirname, '../../');

		// The path to test runner
		// Passed to --extensionTestsPath
		const extensionTestsPath = path.resolve(__dirname, './suite/index');

		const vscodeExecutablePath = await downloadAndUnzipVSCode('stable');
		const [cliPath, ...args] = resolveCliArgsFromVSCodeExecutablePath(vscodeExecutablePath);

		cp.spawnSync(
			cliPath,
			[...args, '--install-extension', EXTENSION_PACK_ID],
			{
				encoding: 'utf-8',
				stdio: 'inherit'
			}
		);

		// Download VS Code, unzip it and run the integration test
		await runTests({ vscodeExecutablePath, extensionDevelopmentPath, extensionTestsPath });
	} catch (err) {
		console.error('Failed to run tests');
		process.exit(1);
	}
}

main();
```
This code is derived from the sample code in this repo's README, and it code works perfectly fine on OSX and Linux and also on Windows if I'm running Node 20.12.1 or earlier. But on Windows using 20.12.2, it doesn't work. `cp.spawnSync()` is apparently silently failing to install the designated extension.
I suspect that this is related to [this change](https://nodejs.org/en/blog/release/v20.12.2#notable-changes), but I have no idea how to work around this. Is there a known fix or workaround?

**Comment by connor4312** [comment]
The workaround for this is passing `shell: true` when calling `spawnSync`

**Comment by jfeingold35** [comment]
@connor4312, okay, that fixes Windows, but it breaks MacOS in the exact same way that Windows was previously broken. Any advice?

**Comment by connor4312** [comment]
Not at the moment, though you could do `shell: process.platform === 'win32'`.

I haven't yet dug into the CVE very much, it seems like a big miss that they rolled out such a disruptive change in a patch release without good migration guidance.

**Comment by ryanluker** [comment]
> Not at the moment, though you could do `shell: process.platform === 'win32'`.
> 
> I haven't yet dug into the CVE very much, it seems like a big miss that they rolled out such a disruptive change in a patch release without good migration guidance.

Thanks, this helped a bunch!
(If this will be a more permanent fix needed, then maybe it should be added to the testing docs?)
https://code.visualstudio.com/api/working-with-extensions/testing-extension#custom-setup-with-vscodetestelectron
