### ISSUE TITLE
Testing does not insert correct env/Script to PATH env var in windows.

### ISSUE THREAD

**Issue by inoa-dmpassy** [microsoft/vscode-test#267]
**Description:**
When you install a Python dependencies, it resides in env/Lib if it's a python package or at env/Script if is an executable.
when you activate the virtual env, it insert those 2 paths into your PATH env var.
When running a python scripts, it uses those paths, however, when running from vscode test runner (not the debugger), it does not insert those paths, relying on the system level Python.

Step to reproduction:
- create an env (used UV)
- ctrl+shift+p, choose interpreter
- reload bash
- install pytest 
- pytest hi.py
```python
 # test.py
def test():
    import os, sys
    print(os.environ['PATH'])
    sys.exit(1) # to print the ouput


# c:\Users\DMpassy\.vscode\extensions\ms-python.python-2024.4.1\python_files\deactivate\powershell;
# C:\Program Files\PowerShell\7;c:\Users\DMpassy\.vscode\extensions\ms-python.python-2024.4.1\python_files\deactivate\powershell;
# C:\Users\DMpassy\Projects\alphatools-main\env/Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;  C:\Users\DMpassy\Projects\alphatools-main\env/Scripts;
#(...)

```
- set  vscode testing with pytest
- run test through the vscode interface
```
# C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\; 
# (...)
# C:\Python39\Scripts\;C:\Python39\;C:\Users\DMpassy\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\DMpassy\AppData\Local\Programs\Python\Python37\;C:\Program Files\Azure Data Studio\bin;C:\Users\DMpassy\AppData\Local\Microsoft\WindowsApps;;C:\Users\DMpassy\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DMpassy\.dotnet\tools;C:\Users\DMpassy\AppData\Roaming\npm
# not a single reference to env.
```

it works just fine with vscode debugging

this breaks calling subprocess.run(), Popen, etc

My computer environment:
windows 11
Python 3.9.13

**Comment by connor4312** [comment]
The test runner does not reuse your system install, data directory, or environment selection. Please ctrl+f for `--install-extension` in the example for how to install extensions in the test runner directory. https://github.com/microsoft/vscode-test?tab=readme-ov-file#usage

You may also need to run commands or other setup to pick the environment once you've done so.
