### ISSUE TITLE
Extension installation is broken on Windows

### ISSUE THREAD

**Issue by EduardSergeev** [microsoft/vscode-test#268]
Attempt to install VSCode extension as a prerequisite of test suite fails on Windows (but works on Linux and MacOS). This is the behaviour of the latest version `2.3.9`.

Example of the code which installs extensions:

```c#
const cliPath = resolveCliPathFromVSCodeExecutablePath(vscodeExecutablePath);

// Install dependent extensions
const dependencies = [
  'jcanero.hoogle-vscode',
  'dramforever.vscode-ghc-simple',
];

const extensionsDir = path.resolve(path.dirname(cliPath), '..', 'extensions');
const userDataDir = path.resolve(extensionsDir, '..', '..', 'udd');

for(const extension of dependencies) {
  const res = cp.spawnSync(cliPath, ['--extensions-dir', extensionsDir, '--install-extension', extension], {
    encoding: 'utf-8',
    stdio: 'inherit'
  });
  console.log(`Res: ${JSON.stringify(res)}`);
}
```

Error produced by this code:

```json
{
    "error": {
        "errno": -4071,
        "code": "EINVAL",
        "syscall": "spawnSync C:\\work\\vscode-haskutil\\.vscode-test\\vscode-win32-x64-archive-1.89.0\\bin\\code.cmd",
        "path": "C:\\work\\vscode-haskutil\\.vscode-test\\vscode-win32-x64-archive-1.89.0\\bin\\code.cmd",
        "spawnargs": [
            "--extensions-dir",
            "C:\\work\\vscode-haskutil\\.vscode-test\\vscode-win32-x64-archive-1.89.0\\extensions",
            "--install-extension",
            "jcanero.hoogle-vscode"
        ]
    },
    "status": null,
    "signal": null,
    "output": null,
    "pid": 0,
    "stdout": null,
    "stderr": null
}
```

Example of test run which experiences this error: [fails on Windows](https://github.com/EduardSergeev/vscode-haskutil/actions/runs/8980804718/job/24665091105#step:7:33) but [works on Ubuntu](https://github.com/EduardSergeev/vscode-haskutil/actions/runs/8980804718/job/24665090939#step:7:46) and [MacOS](https://github.com/EduardSergeev/vscode-haskutil/actions/runs/8980804718/job/24665092706#step:7:39)

**Comment by EduardSergeev** [comment]
> Please see [#266 (comment)](https://github.com/microsoft/vscode-test/issues/266#issuecomment-2085723194)

Yes, I did try this workaround but it did not work for me, I was getting the following errors instead:

```log
Installing extensions...
Error while installing extensions: read ECONNRESET
read ECONNRESET
Res: {"status":1,"signal":null,"output":[null,null,null],"pid":13540,"stdout":null,"stderr":null}
Installing extensions...
Error while installing extensions: read ECONNRESET
read ECONNRESET
Res: {"status":1,"signal":null,"output":[null,null,null],"pid":10720,"stdout":null,"stderr":null}
```

Besides, according to that comment thread this workaround breaks MacOS (and probably Linux) but I believe that the same [extension installation code](https://www.npmjs.com/package/@vscode/test-electron#usage) is supposed to work on all three supported platforms.

It looks like an obvious regression to me (this code did work in older version of `vscode-test` before).

**Comment by EduardSergeev** [comment]
> > Please see [#266 (comment)](https://github.com/microsoft/vscode-test/issues/266#issuecomment-2085723194)
> 
> Yes, I did try this workaround but it did not work for me, I was getting the following errors instead:

Actually it seems to be unrelated intermittent error which does not happen anymore.

Yes, adding `{ shell: true }` does fix the problem on Windows and it can be used on muti-platform tests via condition operator:

```ts
cp.spawnSync(cliPath, ['--extensions-dir', extensionsDir, '--user-data-dir', userDataDir, '--install-extension', extension], {
  shell: process.platform === 'win32' ? true : undefined,
  encoding: 'utf-8',
  stdio: 'inherit'
});
```

By the way, why the sudden change in behavior? Is it because of [this Node security patch](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2)?

**Comment by connor4312** [comment]
I updated our guidance and added a new `runVSCodeCommand` utility that does the right thing automatically
