### ISSUE TITLE
how do you add code coverage

### ISSUE THREAD

**Issue by cazfletch** [microsoft/vscode-test#27]
i want to add code coverage to my extension tests, how do i make code coverage work?

**Comment by octref** [comment]
I don't think this is possible. If you want code coverage you should use unit tests. This is for E2E test that blackbox tests the extension.

**Comment by cazfletch** [comment]
When i try just running my tests using mocha i get the error `Error: Cannot find module 'vscode'` how do i get around this problem?

**Comment by octref** [comment]
`yarn add @types/vscode`, see https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by cazfletch** [comment]
i have `@types/vscode` installed but still get the error.  i'm running `mocha -r ts-node/register -u bdd test/**/**.test.ts`

**Comment by octref** [comment]
Follow setup of https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample, use the [code generator](https://code.visualstudio.com/api/get-started/your-first-extension) or follow this tutorial.

**Comment by cazfletch** [comment]
but they are the e2e tests. How do i run unit tests?

**Comment by octref** [comment]
Maybe choose one testing framework and start use it?
There's nothing specific about unit testing extension. There are many testing frameworks. I can't cover everything.

**Comment by michaeljones** [comment]
For anyone else seeing this, we have run unit test through this project as any of our code that uses things like vscode.Uri essentially needs to be running inside VS Code as it would be challenging to mock out stuff like that. 

We've had some luck with the approach linked from: https://github.com/microsoft/vscode-test/issues/32#issuecomment-771655100 though we have some issues to work out still.
