### ISSUE TITLE
tests don't run in travis or azure pipeline

### ISSUE THREAD

**Issue by cazfletch** [microsoft/vscode-test#28]
When i run my tests in travis or the azure pipeline none of the tests get run i get the following output

```Found .vscode-test/vscode-1.36.1. Skipping download.
[main 2019-07-15T19:19:35.386Z]‌ update#setState idle‌

nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/usr/local"

Run `unset npm_config_prefix` to unset it.

Exit code:   0
Done
```

It never actually gets to my test runner.  It works fine outside of travis or azure pipeline. I also seem to have more success if i run the tests in batches however sometimes batches will get skipped with the same output as above. This happens on mac and linux but mac seems to be worse

**Comment by cazfletch** [comment]
i should add that this has only started happening since moving to `vscode 1.36`

**Comment by octref** [comment]
That's related to your own nvm setup. You can see https://dev.azure.com/vscode/vscode-test/_build?definitionId=15 and https://travis-ci.org/microsoft/vscode-test which are all green based on https://github.com/microsoft/vscode-test/blob/master/.travis.yml and https://github.com/microsoft/vscode-test/blob/master/sample/azure-pipelines.yml.

**Comment by cazfletch** [comment]
It is not my nvm setup i used the same environment you have and my tests either don't run at all or stop part way through see here https://travis-ci.org/IBM-Blockchain/blockchain-vscode-extension/jobs/559151882. The problems don't happen if i use 1.35.1 to run the tests see https://travis-ci.org/IBM-Blockchain/blockchain-vscode-extension/jobs/559327230.

**Comment by octref** [comment]
I'm not familiar with your setup, but this indicated test success https://travis-ci.org/IBM-Blockchain/blockchain-vscode-extension/jobs/559151882#L1742-L1743 and you have failure to find `coverage.json`: https://travis-ci.org/IBM-Blockchain/blockchain-vscode-extension/jobs/559151882#L1749.

**Comment by cazfletch** [comment]
The tests were not successful we have over 1000 tests but only the first around 100 actually run then the vscode process just seems to end and the rest of the tests are not run. Thats why you then get the error with it not finding the coverage file.

I have also seen the same problem locally that the tests don't always run all the way though vscode just stops running.

**Comment by octref** [comment]
Not sure what have changed. If `vscode-test` worked with 1.35.1 but not 1.36.0, that means it's not a bug for `vscode-test` as it's only a thin layer for downloading and launching VS Code.

I suggest opening a issue in https://github.com/microsoft/vscode. It seems you can locally reproduce it, so please write platform and steps for reproducing it from https://github.com/IBM-Blockchain/blockchain-vscode-extension.
