### ISSUE TITLE
Linux builds on Travis are failing

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode-test#33]
Hello,

[Here](https://travis-ci.org/matepek/vscode-catch2-test-adapter/builds/564872592) is the build.

Only linux builds are failing.

I am not doing anything complex: [code](
https://github.com/matepek/vscode-catch2-test-adapter/blob/development/test/runTests.ts)

I could download manually the file.

Any idea whats wrong?

**Comment by Eskibear** [comment]
Same here for me. 
Below are failure logs for two repos which have **NOT** been migrated to `vscode-test` yet. So I imagine it's a vscode issue instead of this package?

https://travis-ci.org/microsoft/vscode-java-test/jobs/566281825
https://travis-ci.org/microsoft/vscode-java-debug/jobs/564857462

**Comment by octref** [comment]
Do you mind trying this? https://code.visualstudio.com/api/working-with-extensions/continuous-integration#travis-ci Note the difference in xvfb.

I have travis definition here and it's passing for me on Linux: https://github.com/microsoft/vscode-test/blob/master/.travis.yml

**Comment by octref** [comment]
I remember a while ago I had this trouble in Vetur and here was my hopeless attempts to fix Linux build on Travis: https://github.com/vuejs/vetur/pull/1343

**Comment by matepek** [comment]
`/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &` solved it.
Thanks.
