### ISSUE TITLE
Support for Opening / Closing Workspace Within Tests?...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-test#38]
hey there :wave:

thanks for the helpful tool :pray:

i'm using `vscode-test` and its supporting bits to drive end-to-end style tests for my extension. one thing i'd like to do is: open a folder / workspace, open a file, scan the file for "problems" and assert against what i find.

the wrinkle i'm running into is that opening a folder / workspace causes my tests to re-run. specifically:

```js
await executeCommand('vscode.openFolder', project.folder.uri);
```

...when run causes a new window to launch (fine) and my test suite to re-run from the start (not so fine).

i realize i can use the `launchArgs` option to open a project folder / workspace upon launch but i want to target a number of project fixtures where each represents a different use-case. naively, i thought i could just open each as part of my setup / teardown stages but that doesn't appear to be a viable approach.

can you recommend a work-around or alternative approach?

**Comment by octref** [comment]
I'd say follow the sample and run multiple `runTest`, each one with different arguments.
I don't think there's an easy way to run tests across multiple projects, since when you switch root folder and enter/exit multi-root, VS Code needs to reload as it needs to reinstantiate all extensions.
