### ISSUE TITLE
Overriding $HOME in tests...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-test#39]
hi again :wave:

i'm currently overriding the `HOME` environment variable in order to isolate side effects from my end-to-end tests and provide repeatable fixtures / environment configuration:

```js
const extensionDevelopmentPath = getPackagesDir();
const extensionTestsPath = path.join(getExtensionDir(), 'test');
const testProjPath = getTestProjectDir();
const extensionTestsEnv = {
	HOME: getOverriddenHomeDir()
};

try {
	await runTests({
		extensionDevelopmentPath,
		extensionTestsPath,
		extensionTestsEnv,
		launchArgs: [
			testProjPath
		]
	});
} catch (error){
	return logErrorAndExit(error);
}
```

seems to work ok but occasionally i get a cryptic error like: 

```
Error: ENOENT: no such file or directory, open '/path/to/my/extension/test/__root__/home/Library/Application Support/Code/storage.json'
```

...which seems to happen when tests fail (but not always).

is there a recommended way to set a custom `$HOME` path?

thanks in advance :pray:

**Comment by octref** [comment]
> is there a recommended way to set a custom $HOME path?

I don't think so. VS Code CLI doesn't really deal with setting different `$HOME` variables AFAIK.
