### ISSUE TITLE
Downloader should make sure a platform correct version exists

### ISSUE THREAD

**Issue by caleywoods** [microsoft/vscode-test#42]
Sorry for the verbose title, anything more succinct is escaping me.

 In `lib/download.ts`'s [downloadAndUnzipVSCode](https://github.com/microsoft/vscode-test/blob/master/lib/download.ts#L164) it runs a check to see if the `downloadedPath` exists and if it does it just console logs its findings and resolves the promise with the path. This seems to assume that the version of VSCode that exists already matches the platform that is currently running the command, this isn't always true.

I encountered this issue earlier when first running a test suite on Windows which downloaded a stable version of VSCode for Windows. Running the same suite in a Linux docker container, which runs through the same `vscode-test\lib\download.ts` code returns the path of the previously downloaded VSCode for Windows which causes the test suite to then fail because the downloader doesn't go deeper into the file structure to make sure a platform appropriate version of VSCode exists.

When the test suite is ran in the Linux container, the downloader sees `.vscode-test/vscode-1.38.1` and returns the path, if it were to venture into this folder it would find `Code.exe` instead of the `/VSCode-linux-x64` folder that would be needed. I went ahead and opened an issue on the repo whose test suite I encountered this on but I felt like it was potentially an upstream fix.

Perhaps I'm being naive in assuming if `process.platform === 'linux'` then the version of VSCode inside of `.vscode-test/vscode-n.nn.n/*` should match that platform?

**Comment by octref** [comment]
I don't want to complicate the logic here too much — if your platform could change between test suite runs, you should clean `.vscode-test`.
