### ISSUE TITLE
Integration tests improvement

### ISSUE THREAD

**Issue by JohnstonCode** [microsoft/vscode-test#45]
Not sure if it is possible but, would it be possible to have a testing API that lets test click and enter text inside the vscode window? This would allow me to automate all of the checks i have to manually do. Something like puppeteer.

**Comment by octref** [comment]
You can use the `TextDocument.applyEdit` API from `vscode`.

**Comment by JohnstonCode** [comment]
Thats not quite what im after. I would like somethnig that would allow me to interact with the UI. For example to right click on a item in the SCM changes list and then click a content option.

**Comment by octref** [comment]
> For example to right click on a item in the SCM changes list and then click a content option.

That's out of the scope of this utility.

**Comment by nadundesilva** [comment]
I am also looking for something similar. Since vscode-test supports opening a VS Code editor for running tests, shouldn't support for actually simulating interactions be supported as well ? Without that support, it feels a bit incomplete for me.

In my opinion, if it is out of the scope of this project, at least some hint as to how we should be doing this in the documentation would help the extension developers a lot.

**Comment by octref** [comment]
This project only helps you to automate extension test by calling VS Code API, which should satisfy most of the cases for testing extensions.
So you should go to https://github.com/Microsoft/vscode asking for API that allows you to do things like:
- Move mouse to (600, 600)
- Click
- Move mouse to a DOM selector
- Right Click

But that's against the VS Code API design principle, see https://code.visualstudio.com/api/extension-capabilities/overview#no-dom-access

If you have **concrete cases** where you cannot properly test an extension with the current API, open issue at microsoft/vscode to discuss.

**Comment by DonJayamanne** [comment]
We (python extension) do this today using puppeteer (https://github.com/microsoft/vscode-python/tree/master/uitests)

**Comment by nadundesilva** [comment]
Thank you @octref & @DonJayamanne ! That is helpful !
