### ISSUE TITLE
[Feature Request] test webviews

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-test#46]
It would be useful if this module could provide utilities for testing webviews. 
Here are some things that might be useful for testing an extension that for example provides a preview of markdown or svg or html:
1. Checking whether or not a webview has opened
2. Checking if there occurs an error in the console of the webview when the webview is opened
3. Getting the html content of the webview to check if it is updating correctly
4. Accessing the webview directly and emulating clicks or mouse movements (`document.querySelector("button").click()`)

Also: Here is an idea what the api for 1. and 3. could look like:
```js
import * as vscode from 'vscode';
import { getWebviews } from 'vscode-test-utils';

test('markdown preview', async () => {
	await vscode.window.showTextDocument('example.md');
	await vscode.window.vscode.commands.executeCommand('markdownPreview.open');
	const markdownWebviews = await getWebviews('markdownPreview');
	expect(markdownWebviews.length).toBe(1);
	const markdownWebview = markdownWebviews[0];
	expect(markdownWebview.html).toContain('<h1>Markdown Example</h1>');
	await setTextDocumentContent('# Markdown Example!!!');
	expect(markdownWebview.html).toContain('<h1>Markdown Example!!!</h1>');
});
```

**Comment by octref** [comment]
@mjbvz I think those would be feature-requst for Webview related APIs, not me.

**Comment by DonJayamanne** [comment]
I believe testing the contents of webviews is out of scope of VS Code. 

It should be something that the extension author needs to do using other testing frameworks.
After all, the HTML is provided to VS Code by the extension.

> Accessing the webview directly and emulating clicks or mouse movements (document.querySelector("button").click())

Something for testing tools like jest, puppeteer or the like.

@octref Though I wouldn't mind if VSC allows the ability to launch this webview such that we can connect to it using puppeteer.
Then again, I don't see us using this much, as I'd use jest and the like to test HTML content (driven though react) or similar tools.

**Comment by octref** [comment]
Yeah, webviews's HTML / JavaScript can be tested even outside of VS Code. @SimonSiefke Your tests are almost like tests for VS Code's Webview functionality in general.
If you have specific issues for integrating your HTML/CSS/JS, please open an issue in the main vscode repo.
