### ISSUE TITLE
Github CI - Tests are not running

### ISSUE THREAD

**Issue by Jefiozie** [microsoft/vscode-test#47]
At our project xlayers we make use of Github CI Actions. When using the `vscode-test` package for testing purposes the test are not running.  Locally I don't have any problems running the test but as the error is not describing an error.

Could you help me out on this topic, [here is the Github Action Visisble](https://github.com/xlayers/xlayers-vscode-extenstion/pull/7/checks?check_run_id=264463206)

If you need any more information let me know.

**Comment by JohnstonCode** [comment]
Having the same issue https://github.com/JohnstonCode/svn-scm/pull/696/checks?check_run_id=277501328

**Comment by JohnstonCode** [comment]
Seems the issue is only present on the `ubuntu` image

**Comment by JohnstonCode** [comment]
My issues was resolved by 
```
- name: Start xvfb
	if: startsWith(matrix.os, 'ubuntu')
	run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

- name: Run tests
	env:
    	CODE_VERSION: ''
    	DISPLAY: ':99.0'
    run: npm run test
```

**Comment by Jefiozie** [comment]
This worked also for me! Thank you 🙏🏻

**Comment by octref** [comment]
I think xvfb is both mentioned in this page https://code.visualstudio.com/api/working-with-extensions/continuous-integration and the sample config for Azure DevOps https://github.com/microsoft/vscode-test/blob/master/sample/azure-pipelines.yml#L25-L29
