### ISSUE TITLE
Test fail to run when tar or unzip are missing with an unhelpful error message

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode-test#50]
The function `unzipVSCode` (https://github.com/microsoft/vscode-test/blob/bcd614f7a13f3422b530f5f07034d9a7b5f3979c/lib/download.ts#L94) should decompress the downloaded archives. It uses the `unzip` or `tar` utilities for that, but does not check the return value of [`child_process.spawnSync()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) and if these utilities are missing, then you get a rather unhelpful error message when running the tests:
``` ShellSession
$ node ./out/test/runTest.js
Downloading VS Code 1.39.2 from https://update.code.visualstudio.com/1.39.2/linux-x64/stable
Downloaded VS Code 1.39.2 into .vscode-test/vscode-1.39.2
Test error: Error: spawn /vscode-obs/.vscode-test/vscode-1.39.2/VSCode-linux-x64/code ENOENT
Exit code:   -2
Done

Failed to run tests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Solution:
check the return values in https://github.com/microsoft/vscode-test/blob/bcd614f7a13f3422b530f5f07034d9a7b5f3979c/lib/download.ts#L110 and https://github.com/microsoft/vscode-test/blob/bcd614f7a13f3422b530f5f07034d9a7b5f3979c/lib/download.ts#L117 and throw an exception if `res.status != null && res.status != 0` or `res.signal != null`.

I'd submit a PR, but getting a CLA approved takes longer than to actually fix this issue...

**Comment by octref** [comment]
Did you submit the CLA and still want to fix this? If not I can also do it.

**Comment by dcermak** [comment]
> Did you submit the CLA and still want to fix this? If not I can also do it.

Please fix it yourself when you have the time, as I would rather not bother our overworked lawyer to review yet another CLA for a patch that is probably only a few lines long.
