### ISSUE TITLE
Can't run extension test when offline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-test#51]
- Be on a bad connector connection, try to run extension tests
- Fails with `Error: getaddrinfo ENOTFOUND update.code.visualstudio.com update.code.visualstudio.com:443`
- There is a copy of vscode downloaded, so this is checking for an update
- vscode-test should ignore any network error as long as it can run

**Comment by octref** [comment]
> vscode-test should ignore any network error as long as it can run

If you don't specify a version, this assumes "latest stable", and "latest stable" is not knowable unless we ask the update server.

I made the change to not validate against server if:
- You specify a version such as `1.40.2`
- `.vscode-test/vscode-1.40.2` exists

**Comment by roblourens** [comment]
But I think that it should also work if a version is not specified, and any version is present. I don't care whether it's actually the very latest version, I just want to run the tests.

**Comment by octref** [comment]
> I just want to run the tests.

Then you should specify to use the locally installed version. Other people might not like that the default behavior not using latest version for testing.

**Comment by OvidijusParsiunas** [comment]
Could you clarify on how to run tests using the locally installed version.
I have set the version in the `package.json` as `"engines": { "vscode": "1.66.2" }` and my `.vscode-test` directory structure looks as follows (I am running my tests on MacOS):
![image](https://user-images.githubusercontent.com/18709577/163678968-4ec57740-e11f-4e24-9308-8f42854253f8.png)

However, upon attempting to execute my tests offline, I still get the following error:
`Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'update.code.visualstudio.com'
}`

**Comment by connor4312** [comment]
I don't think manually specifying a version is an ideal solution. Network unavailability is a transient problem and shouldn't require code changes to resolve.

**Comment by itsdouges** [comment]
Could the same behaviour be implemented for insiders?
