### ISSUE TITLE
Environment variables and PATH not passing through in 1.2.3

### ISSUE THREAD

**Issue by disposedtrolley** [microsoft/vscode-test#52]
Hello! I'm trying to test my VS Code extension which starts a language server by executing a command on the PATH, but none of the system's environment variables seem to be passing through to the test runner. This is causing my tests to fail with an `ENOENT` error as the executable is not able to be located on the PATH.

Despite passing in the entirety of `process.env` to `runTests()`, no environment variables are available in the test runner script specified by `extensionTestsPath`:

```ts
await runTests({
  extensionDevelopmentPath,
  extensionTestsPath,
  extensionTestsEnv: process.env,
  launchArgs: [extensionWorkspacePath, "--disable-extensions"]
});
```

In the extensionTestsPath file:

```ts
export function run(): Promise<void> {
	console.log(process.env)  // prints nothing
}
```

#20

**Comment by disposedtrolley** [comment]
Update: it *may* have something to do with `nvm` and how it alters the `PATH` when a shell is started.

Somehow I had a global installation of `node` in addition to an `nvm` one, which was conflicting with VS Code's shell (see this [Stackoverflow answer](https://stackoverflow.com/a/50584956))

Removing the global installations allowed me to get the production build of the extension to call the language server executable properly, but it still fails under test.

Does the Extension Development Host have its own set of shell parameters?

**Comment by disposedtrolley** [comment]
Update: a little more digging and it looks like `nvm` is indeed broken when running the Extension Development Host.

I get this error on startup:

```
nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "[...]/.nvm/versions/node/v12.13.1"

Run `unset npm_config_prefix` to unset it.
```

which is detailed in this issue - https://github.com/Microsoft/vscode/issues/36987

The fix is to apply this setting:

    "terminal.integrated.shellArgs.osx": []

but I'm unsure how to do it when testing.

**Comment by disposedtrolley** [comment]
Ok this appears to have fixed the issue:

```
await runTests({
  extensionDevelopmentPath,
  extensionTestsPath,
  extensionTestsEnv: {
    ...process.env,
    "npm_config_prefix": ""
  },
  launchArgs: [extensionWorkspacePath, "--disable-extensions"]
});
```

**Comment by octref** [comment]
Glad you found a solution. I'm not very familiar with what nvm is doing.
