### ISSUE TITLE
Pin an insiders version to not auto update

### ISSUE THREAD

**Issue by NilsJPWerner** [microsoft/vscode-test#53]
I have pretty slow internet and so it takes a while to re-download vscode insiders every time there is a new release. I know that a pr was made to explicitly introduce this auto-updating behavior: https://github.com/microsoft/vscode-test/issues/25 but would it be possible to also have the option to pin an insiders version like: `1.42.0-insider` or have an option to not compare to the latest hash?

**Comment by octref** [comment]
That's exactly the reverse of the behavior in #25. In your `runTest` script, I suggest using `fs.existsSync` to check if `.vscode-test/insiders` is present and only run the downloading if it is not there.
