### ISSUE TITLE
Code Coverage for vscode language extension ?

### ISSUE THREAD

**Issue by nvuillam** [microsoft/vscode-test#60]
I have a test suite on language client, that calls language server, and I need to have code coverage of both after running this test suite

I tried (almost)everything ... and succeeded to do nothing

https://github.com/nvuillam/vscode-groovy-lint/blob/master/client/src/test/runTest.ts

Is there somewhere a working example using vscode-test ? 
All that I found were very complex examples not using vscode-test, and i'd like to remain close to vscode standard

Thanks :)

**Comment by octref** [comment]
Tracked in #32. Thanks.
