### ISSUE TITLE
Publish 1.4.0 to npm

### ISSUE THREAD

**Issue by ckant** [microsoft/vscode-test#63]
Would you be able to publish `1.4.0` to npm?
We're facing an issue that would benefit from the change in #56 

Thanks.

**Comment by octref** [comment]
@eamodio Would you mind doing that?

- https://github.com/microsoft/vscode-test/blob/master/CHANGELOG.md is already updated
- `yarn version` for 1.4.0
- `npm publish --otp xxxxxx`

**Comment by jcreedcmu** [comment]
@eamodio do you know when the next release might happen? I'm also very eager to be able to depend on #56.

**Comment by eamodio** [comment]
@ckant @jcreedcmu Sorry for the delay -- 1.4 has now been published
