### ISSUE TITLE
Test process exits with code 'null'

### ISSUE THREAD

**Issue by lakxraju** [microsoft/vscode-test#64]
[Not always] Test process exits with exit code null. Tried to print the thrown error object. But it printed 'Failed',

```
Exit code:   null
Failed to run tests
```

All logs look quite normal. Just that it stopped in the middle. 

I couldn't reproduce this issue. But it occurs sporadically only in Jenkins CI (unix-like nodes). Is there any way to troubleshoot the signal which triggered this? Or has anyone already faced this issue?  Note: I am running the tests using `xvfb-run`

Sometimes, an additional log is also printed:
```
Failed to generate minidump
Exit code:   null
Failed to run tests
```

**Comment by jdneo** [comment]
I have a very similar issue on travis. @lakxraju have you fixed this issue?

**Comment by Kingwl** [comment]
Same too.

**Comment by tonycheang** [comment]
Getting a somewhat similar error in Travis
```bash
Downloading VS Code 1.52.1 from https://update.code.visualstudio.com/1.52.1/linux-x64/stable
Downloaded VS Code 1.52.1 into .vscode-test/vscode-1.52.1
The futex facility returned an unexpected error code.Exit code:   null
Done
Failed to run tests:  SIGABRT
```

**Comment by connor4312** [comment]
Now we'll show the signal that caused the tests to end (e.g. SIGKILL if killed by an OOM killer)
