### ISSUE TITLE
Appveyor is stuck with vscode 1.47

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode-test#68]
1.46 -> working: https://ci.appveyor.com/project/matepek/vscode-catch2-test-adapter/builds/34041042/job/1cp6jlbb12blwyfo
1.47 -> not working: https://ci.appveyor.com/project/matepek/vscode-catch2-test-adapter/builds/34040326

**Comment by AviVahl** [comment]
saw the same in `stylable-intelligence`: https://ci.appveyor.com/project/AlexShemeshWix/stylable-intelligence/builds/34054919

**Comment by bpasero** [comment]
@matepek that sounds like a CI configuration problem to me, not a VSCode issue. You can refer to https://github.com/bpasero/test-ts-pipeline for an example for running the tests on Windows, macOS and Linux in the GH CI.
