### ISSUE TITLE
Make Visual code download url  configurable

### ISSUE THREAD

**Issue by filslo** [microsoft/vscode-test#70]
Hi,

The url to download the visual code binaries archive is hardcoded in thhe code.

Could you make it configurable, so a mirror server could be used  for Continuous Integration server without access to the internet ? 

Otherwise, there is the following error:

 events.js:292
    throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 51.144.164.215:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
   Emitted 'error' event on ClientRequest instance at:
   at TLSSocket.socketErrorListener (_http_client.js:426:9)
   at TLSSocket.emit (events.js:315:20)
  at emitErrorNT (internal/streams/destroy.js:92:8)
   at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
   at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '51.144.164.215',
  port: 443
}

Thanks

**Comment by karuppiah7890** [comment]
@bpasero Since the environment does not have access to the Internet, then it has to use the mirror to even get the latest versions list (stable/insiders) too?

**Comment by karuppiah7890** [comment]
@filslo May I ask if you can use the `.vscode-test` directory and make sure that VS Code is already downloaded and exists? Probably through a Docker image, which you can keep up to date. It will also make the test run faster as you will not have to download VS Code every time then, it will be part of the Docker image.

If Docker image is not a possibility, if some sort of cache is possible, you could try that too.

**Comment by karuppiah7890** [comment]
@bpasero Is this surely going to be implemented? Any thoughts on how to implement this?

I can currently see four URLs related to the download

https://update.code.visualstudio.com/api/releases/stable to get list of stable release versions

https://update.code.visualstudio.com/${version}/${downloadPlatform}/stable to download a stable release based on platform

https://update.code.visualstudio.com/api/update/${platform}/insider/latest to get the latest insider version based on platform

https://update.code.visualstudio.com/latest/${downloadPlatform}/insider to download the latest insider version based on platform

**Comment by karuppiah7890** [comment]
So, the above have to be parameterized and obtained as parameters for `downloadAndUnzipVSCode` I guess? Probably as a third optional argument to avoid breaking changes?

**Comment by connor4312** [comment]
You can pass in a `vscodeExecutablePath` when you call `runTests`, which you could download from the server ahead of time or acquire in another way.
