### ISSUE TITLE
With VS Code 1.49 Tests can no longer run on Linux

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-test#73]
We're getting this on all of our test runs:
```
[5304:0911/170659.592044:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye
```

**Comment by rchiodo** [comment]
I thought maybe adding ```--disable-gpu``` might fix the problem but it doesn't seem to work.

**Comment by rchiodo** [comment]
Here's our args to run tests:

```
    runTests({
        extensionDevelopmentPath: extensionDevelopmentPath,
        extensionTestsPath: path.join(EXTENSION_ROOT_DIR_FOR_TESTS, 'out', 'test', 'index'),
        launchArgs: ['--disable-gpu', '--disable-extensions', workspacePath]
            .concat(channel === 'insiders' ? ['--enable-proposed-api'] : [])
            .concat(['--timeout', '5000']),
        version: channel,
        extensionTestsEnv: { ...process.env, UITEST_DISABLE_INSIDERS: '1' }
    }).catch((ex) => {
        console.error('End Standard tests (with errors)', ex);
        process.exit(1);
    });

```

**Comment by rchiodo** [comment]
Note: This worked fine with 1.48 and earlier.

**Comment by bpasero** [comment]
@rchiodo that sounds like a CI configuration problem to me, not a VSCode issue. You can refer to https://github.com/bpasero/test-ts-pipeline for an example for running the tests on Windows, macOS and Linux in the GH CI.

**Comment by rchiodo** [comment]
It was ubuntu 16. We had to upgrade to Ubuntu 20 and the problem went away. Did VS code (electron) stop supporting Ubuntu 16?
