### ISSUE TITLE
Use "exit" event in runTest.ts

### ISSUE THREAD

**Issue by tal-sapan** [microsoft/vscode-test#74]
Hi,

I am running tests for a vscode extension in a complex CI environment (which involves Jenkins which runs a slave on Kubernetes).
In this setup the "close" event is not called when the vscode process ends, but "exit" is called.
Since `runTests` only listens to "close", this makes it difficult to use the `vscode-test` library for my tests as it is currently written.

According to the `ChildProcess` events [documentation](https://nodejs.org/api/child_process.html#child_process_event_close):
> The 'exit' event is emitted after the child process ends. [...]
> When the 'exit' event is triggered, child process stdio streams might still be open.

And:
> The 'close' event is emitted when the stdio streams of a child process have been closed. This is distinct from the 'exit' event, since multiple processes might share the same stdio streams.

This means that "exit" is always called when the process ends.

Could you consider changing this code:
https://github.com/microsoft/vscode-test/blob/9aade080626e0a237c17d230f4fccb926776eec7/lib/runTest.ts#L128
to listen to "exit" instead of (or in addition to) "close" or add an option for it in the `TestOptions`?

If you would like, I could contribute a PR for this. I have already tested this change in several environments (including Windows, Linux and Mac) and it seems to work without a problem.

Thanks,
Tal

**Comment by bpasero** [comment]
I think it is fair to add another handler for `exit` that kicks in when `close` has not been called yet. But it should not resolve the same promise twice.

**Comment by tal-sapan** [comment]
Hi,

Thank you! I created a pull request with the fix (#75).

Best regards,
Tal

**Comment by ryanthered** [comment]
We are also seeing this issue. For us runTests hangs occasionally at the end of running tests. Adding an exit handler as described seems to fix the issue, but we are still investigating whether we have a stream open and not receiving 'close' events.

**Comment by bpasero** [comment]
I created `1.4.1` but miss the permissions to publish to npm, @eamodio can you do that please
