### ISSUE TITLE
CI failures related to path length

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode-test#76]
Our CI jobs fail to run against the insiders version of VS Code, but works fine against the stable version.  I'm under the impression that the total length of the path is the root cause.

Using `downloadAndUnzipVSCode`, our AWS CodeBuild based jobs install to `C:\codebuild\tmp\output\src259930023\src\github.com\aws\aws-toolkit-xxxxxxxxxxxxxx\.vscode-test\vscode-insiders`

Executing a version check as follows then fails
`"C:\codebuild\tmp\output\src259930023\src\github.com\aws\aws-toolkit-xxxxxxxxxxxxxx\.vscode-test\vscode-insiders\bin\code-insiders.cmd" --version`

If I fork the repo, and rename it something smaller, there is no issue running either insiders/stable versions of VS Code.

Would it be reasonable to provide an optional install location to `downloadAndUnzipVSCode` ?

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-test/commit/a20b727c52769b0a5c2a24de9ffa00515bd8e3b4.

Also should shave some time off your CI by downloading and decompressing in parallel 🙂
