### ISSUE TITLE
runTests doesn't respect the .vscode folder in the opened workspace

### ISSUE THREAD

**Issue by tamj0rd2** [microsoft/vscode-test#79]
I have a "Run Extension" launch task that starts vscode so that I can test my extension. I have a folder called `test-environment` that vscode is supposed to open directly into. When I run my launch task, it opens that folder but none of the settings in `test-environment/.vscode` are being respected. When I test my extension, I want it to use the typescript.tsdk in the test-environment/node_modules, not the version of typescript bundled with vscode. I have the same issue when I run the extension tests via the terminal.

Here's my launch json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run Extension",
      "type": "extensionHost",
      "request": "launch",
      "args": [
        "${workspaceFolder}/test-environment",
        "--disable-extensions",
        "--extensionDevelopmentPath=${workspaceFolder}/packages/extension"
      ],
      "outFiles": ["${workspaceFolder}/packages/extension/out/**/*.js"],
      "preLaunchTask": "${defaultBuildTask}",
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```

Here's my run-tests file:

```typescript
async function main(): Promise<void> {
  try {
    // Download VS Code, unzip it and run the integration test
    await runTests({
      version: 'stable',
      launchArgs: [TEST_ENV_DIR, '--disable-extensions'],
      // The folder containing the Extension Manifest package.json
      extensionDevelopmentPath: EXTENSION_ROOT_DIR,
      // The path to test runner
      extensionTestsPath: resolve(E2E_ROOT_DIR, 'out/tests/index'),
    })
  } catch (err) {
    console.error('Failed to run tests')
    process.exit(1)
  }
}
```

Folder structure:
```
test-environment/
  .vscode/
    settings.json
  testing.ts
  tsconfig.json
  etc...
```

Here is the test-environment/.vscode/settings.json contents:
```json
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "telemetry.enableTelemetry": false,
  "typescript.tsserver.trace": "messages",
}
```

![image](https://user-images.githubusercontent.com/20561445/102691374-ea68bd80-4203-11eb-86d7-cb8321eb7788.png)

**Comment by tamj0rd2** [comment]
I've created a test-workspace.code-workspace file in this directory. Is there a way for me to get the runTests to open that workspace configuration directly? Maybe that would solve the issue?

**Comment by apupier** [comment]
Can you log the `TEST_ENV_DIR` value? Maybe it is not pointing to the correct place. (it migth be tricky depending from the test are executed)

**Comment by lovettchris** [comment]
I have the same problem, I know my runtest is opening the right folder, because I see the files in the explorer tab, I see the .vscode folder, but the settings.json in there is being ignored.  If I open the same folder as a user using the same .vscode-test version of code.exe then the settings.json is honored.  So something weird about runtest for sure...
