### ISSUE TITLE
Feature Request: Be able to stub out VS code UI in a test (and only a test)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-test#80]
I frequently find myself wanting to run a VS code command in a test, but that command may bring up other UI that I need the test to force to a specific value.

It would be super useful if there were some way to stub out parts of VS code ui.

Example:

```
sinon.stub(window, 'showQuickPick').resolves(myQuickPickItem)
```

This would likely require changes to VS code to support though.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/94746
