### ISSUE TITLE
Add `code-test` CLI

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-test#81]
Right now we require a `runTests` script. However we could serve 99% of users with a CLI instead, which would be easier to invoke and more friendly with argument passing.

**Comment by felipecrs** [comment]
This would be a super useful feature.

**Comment by remcohaszing** [comment]
Is there anything blocking this? My PR has been ready for about a year, but isn’t getting any attention.

**Comment by connor4312** [comment]
This is now done, docs are here: https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md#quick-setup-the-test-cli
