### ISSUE TITLE
runTests does not work behind proxy

### ISSUE THREAD

**Issue by sieukrem** [microsoft/vscode-test#82]
Since update to vscode-test 1.5 our tests are failing in the pipeline behind proxy.

```
(node:69) UnhandledPromiseRejectionWarning: Failed to get JSON
(node:69) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Failed to parse response from https://update.code.visualstudio.com/api/releases/stable as JSON
(node:80) UnhandledPromiseRejectionWarning: Failed to get JSON
```

I would like to know if the proxy is stil supported, before  I start additional debugging on my side.

**Comment by connor4312** [comment]
Thanks for the issue! We do still support proxies, but in housekeeping for 1.5.0 I updated our outdated dependencies [which included](https://github.com/microsoft/vscode-test/commit/e9d2dca994ac3c87253d97e7f680860cab68ee10#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) the proxy handling modules.

Can you provide info about how your proxy is set up so I can try to reproduce your issue?

**Comment by sieukrem** [comment]
Meanwhile I tried out to run docker container running  behind proxy in the pipeline in my local environment without proxy. It works .
I do not know the real proxy software, but I know how I setup it in the pipeline so that `curl` and `npm` are working.
```
$export HTTP_PROXY=http://<proxy ip>:<port>
$export HTTPS_PROXY=https://<proxy ip>:<port>
$export http_proxy=$HTTP_PROXY
$export https_proxy=$HTTPS_PROXY
$npm config set proxy $http_proxy
$npm config set https-proxy $https_proxy
```
```
$npm -v
6.14.10
$node -v
v12.20.1
```

**Comment by sieukrem** [comment]
I will try to downgrade the proxy packages next week.
