### ISSUE TITLE
Debugger connection lost after executing "vscode.openFolder" command

### ISSUE THREAD

**Issue by alberto-bc** [microsoft/vscode-test#87]
VS Code version: 1.54.2
Platform: Windows 10
[debugger_disconnects.zip](https://github.com/microsoft/vscode-test/files/6126815/debugger_disconnects.zip)

The project to reproduce is an extension generated using [`yo code`](https://code.visualstudio.com/api/get-started/your-first-extension)

Steps to reproduce
- Open the project
- Run `npm ci` in a terminal window
- Open `extension.test.ts` file
- Place a breakpoint in line 15 (log statement)
- Select `Extension Test` for debugging
- Start debugging

Observed results
The breakpoint hits, then after a few seconds the debugger loses connection

Notice that if we remove the `vscode.openFolder` command everything works as expected.

**Comment by connor4312** [comment]
This is an effect of the design of VS Code -- tests run in the extension host, and extensions hosts are per-workspace. Opening a different folder (i.e. a new workspace) will give you a new extension host and stop the run that was previously running tests.

**Comment by alberto-bc** [comment]
Is there a workaround for this? i.e. attach the debugger to the new extension host?

**Comment by connor4312** [comment]
I don't believe there's any workaround
