### ISSUE TITLE
Tests get stuck when executing "vscode.openFolder" command in different test files

### ISSUE THREAD

**Issue by alberto-bc** [microsoft/vscode-test#88]
VS Code version: 1.54.2
Platform: Windows 10
Issue probably related: [87](https://github.com/microsoft/vscode-test/issues/87)

Problem
Running these 
[tests_stuck.zip](https://github.com/microsoft/vscode-test/files/6126874/tests_stuck.zip)
tests via command-line results in an infinite loop

Steps to reproduce
- Unzip example
- Run `npm ci` in a terminal window
- Run `npm run test`

Observed behavior
Tests get stuck in an infinite loop, switching between opening workspaceA and opening workspaceB

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-test/issues/87 -- we don't support this scenario
