### ISSUE TITLE
Disable download progress in CI environments

### ISSUE THREAD

**Issue by ext** [microsoft/vscode-test#90]
I'd like to have an option (automatic or manual) to disable download progress in my CI builds as the output just becomes a mess:

```
Downloading VS Code 1.33.0 from https://update.code.visualstudio.com/1.33.0/linu
x-x64/stableDownloading VS Code 1.33.0 from https://update.code.visualstudio.com
/1.33.0/linux-x64/stable: 48500/68367968 (0%)Downloading VS Code 1.33.0 from htt
ps://update.code.visualstudio.com/1.33.0/linux-x64/stable: 228724/68367968 (0%)D
ownloading VS Code 1.33.0 from https://update.code.visualstudio.com/1.33.0/linux
-x64/stable: 408948/68367968 (1%)Downloading VS Code 1.33.0 from https://update.
code.visualstudio.com/1.33.0/linux-x64/stable: 998772/68367968 (1%)Downloading V
SCode 1.33.0 from https://update.code.visualstudio.com/1.33.0/linux-x64/stable:
1654132/68367968 (2%)Downloading VS Code 1.33.0 from https://update.code.visuals
[...]
```

It seems to be because the [`printProgress`](https://github.com/microsoft/vscode-test/blob/main/lib/download.ts#L83) function does no checking if ANSI escape codes are supported by the terminal or if the output is attached to a terminal at all.

I think it would be useful if [ `TestOptions`](https://github.com/microsoft/vscode-test/blob/main/lib/runTest.ts#L9) contained an option `disableProgress: boolean` or `color: boolean` so I can set it properly when running tests, for instance:

```js
const isCI = require("is-ci");
await runTests({
  disableProgress: isCI,
});
```

Alternatively the `printProgress` could use a function such as `tty.isAtty` to determine automatically if it should display progress. (Or depend on a third-party library but I am rather happy that this tool has very few dependencies)

If you want I could write a PR to support this.

**Comment by connor4312** [comment]
Sure, tty.isAtty sounds good. PRs welcome.
